### ISSUE TITLE
This does not work

### ISSUE THREAD

**Issue by jemsz** [omkarcloud/g2-scraper#3]
The default targets are all located in folder **cache\get_products**
Adding new products, deleting the cache folder and running the script will error

Error: 500 {'status': 500, 'message': 'Server Error'}
Could not get data for 1 product due to Unknown Error.

**Comment by Chetan11-dev** [comment]
Resolved

**Comment by nick-choudhary** [comment]
still doesn't work

**Comment by Chetan11-dev** [comment]
Try on omkar cloud website

**Comment by nick-choudhary** [comment]
there also not working. rapidapi one also not working, apify one aswll

**Comment by Chetan11-dev** [comment]
https://github.com/user-attachments/assets/83a23603-f221-4d66-9930-199ccccc5def
Works, see

**Comment by nick-choudhary** [comment]
These are cached that's why, nothing else is working. try...
